name: Hello

on:
  push:
    branches: [ test-actions ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Step 1 - checkout code
        uses: actions/checkout@v2
      - name: Step 2 - Run a one-line script
        run: echo Hello, world!
      - name: Step 3 - Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Step 4 - Print env variables
        run: "Get-ChildItem Env: | Sort-Object Name"
